apiVersion: apps/v1
kind: Deployment
metadata:
  name: firevault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firevault-app
  template:
    metadata:
      labels:
        app: firevault-app
    spec:
      containers:
        - name: firevault-container
          image: firevaultregistry.azurecr.io/firevault-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: firevault-k8s-secret
                  key: AZURE_STORAGE_ACCOUNT_NAME 
            
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: firevault-k8s-secret
                  key: AZURE_STORAGE_ACCOUNT_KEY
            
            - name: AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: firevault-k8s-secret
                  key: AZURE_CONTAINER_NAME

            - name: PORT
              value: "3000"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-sync"