apiVersion: v1
kind: Service
metadata:
  name: firevault-service
spec:
  type: LoadBalancer       
  selector:
    app: firevault-app     
  ports:
    - protocol: TCP
      port: 80             
      targetPort: 3000   